.\" generated with Ronn-NG/v0.8.0
.\" http://github.com/apjanke/ronn-ng/tree/0.8.0
.TH "TIME_PRIVACY" "1" "April 2020" "uwt" "uwt Manual"
.SH "NAME"
\fBtime_privacy\fR \- keep your time private
.P
.SH "SYNOPSIS"
\fBtime_privacy\fR \fI\%#OPTIONS\fR
.SH "DESCRIPTION"
Timeprivacy can keep your time private\. You can create wrappers for applications (such as git, gpg, etc\.) and timeprivacy will feed those applications with a fake time, which obfuscates at which time you really used that applications (such as when you made the git commit or when you signed that document)\.
.P
It does NOT set your time zone to UTC\.
.SH "OPTIONS"
.IP "\[ci]" 4
\-h
.IP
help
.IP "\[ci]" 4
\-d day
.IP
day
.IP "\[ci]" 4
\-m month
.IP
month
.IP "\[ci]" 4
\-y year
.IP
year
.IP "\[ci]" 4
\-i seconds
.IP
increment in seconds (0\-60)
.IP "\[ci]" 4
\-r \fIseconds\fR
.IP
random increment in seconds (0\-60)
.IP "\[ci]" 4
\-f history folder
.IP
history folder
.IP "" 0
.SH "EXIT CODES"
0 Success
.P
1 Error
.SH "EXAMPLE"
\fBtime_privacy\fR
.P
\fBtime_privacy \-d 30 \-m 12 \-y 2013 \-i 10 \-f /tmp/\fR
.P
\fBsudo time_privacy \-d 30 \-m 12 \-y 2013 \-r \-f /tmp/\fR
.SH "DEMONSTRATION"
Create a file /usr/local/bin/tpdate\.
.IP "" 4
.nf
#!/bin/bash
faketime "$(time_privacy)" date "$@"
.fi
.IP "" 0
.P
Try\.
.IP "" 4
.nf
~ $ tpdate
Fri May  3 00:00:01 UTC 2013
~ $ tpdate
Fri May  3 00:00:02 UTC 2013
~ $ tpdate
Fri May  3 00:00:03 UTC 2013
~ $ tpdate
Fri May  3 00:00:04 UTC 2013
~ $ tpdate
Fri May  3 00:00:05 UTC 2013`
.fi
.IP "" 0
.P
Let\'s try something more interesting\. Let\'s add timeprivacy to git\. We need to create a wrapper\. It will take precedence over /usr/bin/git, thus run faketime and timeprivacy before git itself\. Create a file /usr/local/bin/git\.
.IP "" 4
.nf
#!/bin/bash
prog=git
faketime "$(time_privacy)" $prog "$@"
.fi
.IP "" 0
.SH "UPSTREAMING"
This script has been merged \fI\%https://github\.com/wolfcw/libfaketime/pull/16#issuecomment\-17706741\fR into libfaketime \fI\%https://github\.com/wolfcw/libfaketime\fR (src \fI\%https://github\.com/wolfcw/libfaketime/blob/master/src/timeprivacy\fR)\.
.P
It may show up as \fBtimeprivacy\fR in the faketime package at some point\. Therefore timeprivacy is called time_privacy to avoid a conflict when that happens\.
.SH "DEVELOPMENT / PATCHES / FEATURE REQUESTS / BUG REPORTS"
You can leave feedback and/or contribute in adrelanos\'s timeprivacy github repository \fI\%https://github\.com/adrelanos/timeprivacy\fR or to libfaketime \fI\%https://github\.com/wolfcw/libfaketime/issues\fR and mention @adrelanos as far as timeprivacy is concerned\.
.SH "SEE ALSO"
\fBfaketime\fR(1)
.SH "AUTHOR"
This man page has been written by Patrick Schleizer (adrelanos@whonix\.org)\.
