#!/bin/bash

## This file is part of Whonix.
## Copyright (C) 2012 - 2014 Patrick Schleizer <adrelanos@riseup.net>
## See the file COPYING for copying conditions.

## Please use "/etc/whonix.d/50_uwt_user" for your custom configuration,
## which will override the defaults found here. When Whonix is updated, this
## file may be overwritten.

## Enable or disable all uwt stream isolation wrappers globally.
uwtwrapper_global="1"

## Do not touch the following line!
declare -A -g uwtwrapper

## The specific wrappers overrule the global wrapper setting on a by case base.
## Comment them in/out and set to 0 (disable) or 1 (enable) as needed.
#uwtwrapper["/usr/bin/git"]="1"
#uwtwrapper["/usr/bin/apt-get"]="1"
#uwtwrapper["/usr/bin/curl"]="0"
#uwtwrapper["/usr/bin/gpg"]="0"
#uwtwrapper["/usr/bin/mixmaster-update"]="1"
#uwtwrapper["/usr/bin/rawdog"]="1"
#uwtwrapper["/usr/bin/ssh"]="0"
#uwtwrapper["/usr/bin/wget"]="0"
#uwtwrapper["/usr/bin/yum"]="0"

#####################################################################
## Do not change anything below unless you know what you are doing! #
#####################################################################

## Do not touch the following line!
declare -A -g uwtport

uwtport["/usr/bin/git"]="9107"
uwtport["/usr/bin/apt-get"]="9104"
uwtport["/usr/bin/curl"]="9117"
uwtport["/usr/bin/gpg"]="9105"
uwtport["/usr/bin/mixmaster-update"]="9120"
uwtport["/usr/bin/rawdog"]="9118"
uwtport["/usr/bin/ssh"]="9106"
uwtport["/usr/bin/wget"]="9109"
uwtport["/usr/bin/aptitude"]="9124"
uwtport["/usr/bin/yum"]="9125"
uwtport["/usr/bin/yumdownloader"]="9125"

uwtwrapper_gateway_ip_detection() {
   if [ "$UWT_DEV_PASSTHROUGH" = "1" ]; then
      ## Can be the case when building Whonix from source code.
      uwtwrapper_gateway_ip="UWT_DEV_PASSTHROUGH"
      return 0
   fi

   if command -v qubesdb-read >/dev/null 2>&1 ; then
      ## '/qubes-vm-type' is either 'AppVM', 'ProxyVM', 'NetVM' or 'TemplateVM'
      qubes_vm_type="$(qubesdb-read /qubes-vm-type)"
      if [ "$qubes_vm_type" = "TemplateVM" ] || [ -f "/usr/share/anon-ws-base-files/workstation" ]; then
         uwtwrapper_gateway_ip="$(qubesdb-read /qubes-gateway)"
         return 0
      fi
   fi

   if [ -f "/usr/share/anon-ws-base-files/workstation" ]; then
      uwtwrapper_gateway_ip="10.152.152.10"
      return 0
   fi

   if [ -f "/usr/share/anon-gw-base-files/gateway" ]; then
      uwtwrapper_gateway_ip="127.0.0.1"
      return 0
   fi

   error "\
uwt wrapper could not determine if this is Whonix-Workstation or Whonix-Gateway.
Variable uwtwrapper_gateway_ip does not exist early enough in /etc/uwt.d.
If you are using a Custom-Workstation, please consider installing the
anon-gw-base-files or anon-ws-base-files package.
If you are not using a Custom-Workstation: please report this bug!"
}

uwtwrapper_gateway_ip_detection

## Technical Comment:
## - This file gets sourced by uwt wrappers.
## - "-" in variable names is forbidden by bash. Therefore we use
##   only variable names without "-". For reading the correct variable
##   names without "-", the "-" will get temporarily removed from the
##   variable name of the file.
