#!/bin/bash

## Copyright (C) 2012 - 2020 ENCRYPTED SUPPORT LP <adrelanos@riseup.net>
## See the file COPYING for copying conditions.

## Feel free to delete this file.

## Output uwt settings.
## https://phabricator.whonix.org/T73
if test -x /usr/lib/uwt_settings_show ; then
   /usr/lib/uwt_settings_show
fi
