#!/bin/bash

## Copyright (C) 2012 - 2021 ENCRYPTED SUPPORT LP <adrelanos@whonix.org>
## See the file COPYING for copying conditions.

## Feel free to delete this file.

## Output uwt settings.
## https://phabricator.whonix.org/T73
if test -x /usr/bin/uwt-settings-show ; then
   /usr/bin/uwt-settings-show
fi
